name = "edgetunnel-vless"
main = "worker.js"
compatibility_date = "2025-11-04"
keep_vars = false

[vars]
UUID = "bd14d931-06ff-4ec6-9f02-33cec5bbb9f0"
ADMIN = "bd14d931-06ff-4ec6-9f02-33cec5bbb9f0"
HOST = "shyvpn.cc.cd"
SUB = "sub.cmliussss.workers.dev"
CFIP_DATA_URL = "https://test.shyvpn.cc.cd/api/result"
CFST_PANEL_URL = "https://test.shyvpn.cc.cd/"
DISABLE_LOGIN = "true"
DEBUG = "false"
SUBSCRIBE_ORIGIN = "https://shyvpn.cc.cd"

[[kv_namespaces]]
binding = "KV"
id = "54e93fff8c53470b8984a349d29eff3c"
